### ISSUE TITLE
Timer size assertion error on Linux

### ISSUE THREAD

**Issue by ekliot** [cr15th0f3r/odin-box2d#3]
I get the following error trying to compile:
```
assertions.odin(4:1) Error: Compile time assertion: size_of(Timer) == 8
        #assert(size_of(Timer) == 8)
```

I'm on Linux, I see [here](https://github.com/cr1sth0fer/odin-box2d/blob/main/base.odin#L39) (and in the [source](https://github.com/erincatto/box2c/blob/1d7d1cf14722a06f6a7b1c3b0850e70bcbec8558/include/box2d/base.h#L93-L95)) that `Timer` is defined with two `u64` members, making its size 16. 

Updating the assertion to 16 passes compilation, but I also see that the assertions are automatically built with a `.bat`.

**Comment by cr1sth0fer** [comment]
Fixed the assertions on linux.

Those binaries was outdated, I did build it using WSL, but I dont know if is going to work.

**Comment by ekliot** [comment]
Thank you!
